-- ============================================================
-- Snowpark Container Services - Environment Setup
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Create a dedicated role for the project
CREATE ROLE IF NOT EXISTS CONTAINER_USER_ROLE;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE CONTAINER_USER_ROLE;

GRANT ROLE CONTAINER_USER_ROLE TO ROLE ACCOUNTADMIN;

-- Create project resources
USE ROLE CONTAINER_USER_ROLE;

CREATE DATABASE IF NOT EXISTS CONTAINER_HOL_DB;
USE DATABASE CONTAINER_HOL_DB;
USE SCHEMA PUBLIC;

CREATE WAREHOUSE IF NOT EXISTS CONTAINER_HOL_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE;

-- Stores SPCS service specification files
CREATE STAGE IF NOT EXISTS SPECS
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Persistent volume stage used by the Jupyter service
CREATE STAGE IF NOT EXISTS VOLUMES
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);
